timeout: 0

/LosTacOS
    protocol: multiboot2
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/font.psf.gz
    module_string: font.psf.gz
    module_path: boot():/boot/rootfs.tar.gz
    module_string: rootfs.tar.gz
