#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

SYSROOT="$HOME/.ltos/toolchain/sysroot"

OUT="$1"
shift


exec ld \
    -T $HOME/.ltos/linker.ld \
    -nostdlib \
    -o $OUT \
    $SYSROOT/lib/crt0.o \
    $@ \
    $SYSROOT/usr/lib/libc.a
